#!/bin/sh
passwd root<<EOF
123456..
123456..
EOF
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin/PermitRootLogin/g' /etc/ssh/sshd_config
service sshd restart