#!-*- coding:utf8 -*-
import logging.handlers

formatter=logging.Formatter("%(asctime)s %(levelname)s %(message)s")

basePerformanceFileHandler = logging.handlers.RotatingFileHandler('logs/basePerformance.log','a')
basePerformanceStreamHandler = logging.StreamHandler()
basePerformanceFileHandler.setFormatter(formatter)
basePerformanceStreamHandler.setFormatter(formatter)
basePerformanceLogger = logging.getLogger("basePerformance_logger")
basePerformanceLogger.setLevel(logging.INFO)
basePerformanceLogger.addHandler(basePerformanceFileHandler)
basePerformanceLogger.addHandler(basePerformanceStreamHandler)

stabilityIperfFileHandler = logging.handlers.RotatingFileHandler('logs/stabilityIperf.log','a')
stabilityIperfStreamHandler = logging.StreamHandler()
stabilityIperfFileHandler.setFormatter(formatter)
stabilityIperfStreamHandler.setFormatter(formatter)
stabilityIperfLogger = logging.getLogger("stabilityIperf_logger")
stabilityIperfLogger.setLevel(logging.INFO)
stabilityIperfLogger.addHandler(stabilityIperfFileHandler)
stabilityIperfLogger.addHandler(stabilityIperfStreamHandler)

stabilityMemtesterFileHandler = logging.handlers.RotatingFileHandler('logs/stabilityMemtester.log','a')
stabilityMemtesterStreamHandler = logging.StreamHandler()
stabilityMemtesterFileHandler.setFormatter(formatter)
stabilityMemtesterStreamHandler.setFormatter(formatter)
stabilityMemtesterLogger = logging.getLogger("stabilityMemtester_logger")
stabilityMemtesterLogger.setLevel(logging.INFO)
stabilityMemtesterLogger.addHandler(stabilityMemtesterFileHandler)
stabilityMemtesterLogger.addHandler(stabilityMemtesterStreamHandler)

stabilityUnixbenchFileHandler = logging.handlers.RotatingFileHandler('logs/stabilityUnixbench.log','a')
stabilityUnixbenchStreamHandler = logging.StreamHandler()
stabilityUnixbenchFileHandler.setFormatter(formatter)
stabilityUnixbenchStreamHandler.setFormatter(formatter)
stabilityUnixbenchLogger = logging.getLogger("stabilityUnixbench_logger")
stabilityUnixbenchLogger.setLevel(logging.INFO)
stabilityUnixbenchLogger.addHandler(stabilityUnixbenchFileHandler)
stabilityUnixbenchLogger.addHandler(stabilityUnixbenchStreamHandler)

stabilitySysbenchFileHandler = logging.handlers.RotatingFileHandler('logs/stabilitySysbench.log','a')
stabilitySysbenchStreamHandler = logging.StreamHandler()
stabilitySysbenchFileHandler.setFormatter(formatter)
stabilitySysbenchStreamHandler.setFormatter(formatter)
stabilitySysbenchLogger = logging.getLogger("stabilitySysbench_logger")
stabilitySysbenchLogger.setLevel(logging.INFO)
stabilitySysbenchLogger.addHandler(stabilitySysbenchFileHandler)
stabilitySysbenchLogger.addHandler(stabilitySysbenchStreamHandler)


stabilityHeatFileHandler = logging.handlers.RotatingFileHandler('logs/stabilityHeat.log','a')
stabilityHeatStreamHandler = logging.StreamHandler()
stabilityHeatFileHandler.setFormatter(formatter)
stabilityHeatStreamHandler.setFormatter(formatter)
stabilityHeatLogger = logging.getLogger("stabilityHeat_logger")
stabilityHeatLogger.setLevel(logging.INFO)
stabilityHeatLogger.addHandler(stabilityHeatFileHandler)
stabilityHeatLogger.addHandler(stabilityHeatStreamHandler)

stabilityLoadbalancerFileHandler = logging.handlers.RotatingFileHandler('logs/stabilityLoadbalancer.log','a')
stabilityLoadbalancerStreamHandler = logging.StreamHandler()
stabilityLoadbalancerFileHandler.setFormatter(formatter)
stabilityLoadbalancerStreamHandler.setFormatter(formatter)
stabilityLoadbalancerLogger = logging.getLogger("stabilityLoadbalancer_logger")
stabilityLoadbalancerLogger.setLevel(logging.INFO)
stabilityLoadbalancerLogger.addHandler(stabilityLoadbalancerFileHandler)
stabilityLoadbalancerLogger.addHandler(stabilityLoadbalancerStreamHandler)

stabilityFioFileHandler = logging.handlers.RotatingFileHandler('logs/stabilityFio.log','a')
stabilityFioStreamHandler = logging.StreamHandler()
stabilityFioFileHandler.setFormatter(formatter)
stabilityFioStreamHandler.setFormatter(formatter)
stabilityFioLogger = logging.getLogger("stabilityFio_logger")
stabilityFioLogger.setLevel(logging.INFO)
stabilityFioLogger.addHandler(stabilityFioFileHandler)
stabilityFioLogger.addHandler(stabilityFioStreamHandler)

stabilityObjectStorageFileHandler = logging.handlers.RotatingFileHandler('logs/stabilityObjectStorage.log','a')
stabilityObjectStorageStreamHandler = logging.StreamHandler()
stabilityObjectStorageFileHandler.setFormatter(formatter)
stabilityObjectStorageStreamHandler.setFormatter(formatter)
stabilityObjectStorageLogger = logging.getLogger("stabilityObjectStorage_logger")
stabilityObjectStorageLogger.setLevel(logging.INFO)
stabilityObjectStorageLogger.addHandler(stabilityObjectStorageFileHandler)
stabilityObjectStorageLogger.addHandler(stabilityObjectStorageStreamHandler)